version: '3'
services:
  redis:
    image: 'redis:latest'
  api:
    depends_on:
      - redis
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 80:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIXER_API_KEY=7a07d0f0c3ff79174db67fe92bc7142d